### ISSUE TITLE
TX post RPC errors not passed to client

### ISSUE THREAD

**Issue by philippem** [Blockstream/electrs#132]
When broadcasting a tx using POST to /tx, errors from the RPC request are not returned to the client; the client, including esplora, now only sees "RPC error":

client:

```
 % curl -X POST localhost:3001/tx
RPC error%                                                                   
```

electrs:
```
INFO handle POST /tx
DEBUG RPC HTTP 500 error: {"result":null,"error":{"code":-22,"message":"TX decode failed. Make sure the tx has at least one input."},"id":179}
WARN HttpError(400, "RPC error")
```

This behaviour may have changed recently?

**Comment by shesek** [comment]
I opened #133 with a fix.

> This behaviour may have changed recently?

Looking at the code, this does not appear to be a regression - [the faulty line](https://github.com/Blockstream/electrs/blame/new-index/src/rest.rs#L992) was there since the [2019 commit that introduced](https://github.com/Blockstream/electrs/commit/1b85305f16b520511f8df94bace928b75d47740c) the transaction broadcast endpoint.

However I think that I do remember seeing useful RPC errors for transaction broadcast in the past... not quite sure how though.
